import{i as p,a as w,S as b}from"./assets/vendor-0c7dbcfa.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();let n=1;const d=document.getElementById("search-form"),c=document.querySelector(".gallery"),l=document.querySelector(".js-load");d.addEventListener("submit",_);l.addEventListener("click",L);async function L(){n+=1;try{const r=await u(d.elements.searchQuery.value,n);c.innerHTML+=f(r),n>=r.totalPages&&l.classList.replace("load-more","load-more-hidden"),h.refresh(),m()}catch(r){console.error("error",r),p.error({title:"Error",message:"Oops! Something went wrong! Try reloading the page!",position:"topRight"})}}async function _(r){r.preventDefault(),n=1;const s=r.currentTarget.elements.searchQuery.value;try{const a=await u(s,n);a.data.length===0?(c.innerHTML="",l.classList.replace("load-more","load-more-hidden"),p.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight"})):(c.innerHTML=f(a),n<a.totalPages&&l.classList.replace("load-more-hidden","load-more")),h.refresh(),m()}catch(a){console.error("error",a)}}function m(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}async function u(r,s){const t=`https://pixabay.com/api/?key=40948305-cf809bb8656872e1f12174930&q=${r}&page=${s}&per_page=${40}&image_type=photo&orientation=horizontal&safesearch=true`;try{const o=await w.get(t);if(o.data&&o.data.hits)return{data:o.data.hits,totalPages:Math.ceil(o.data.totalHits/40)};throw console.error("Invalid response format:",o),new Error("Invalid response format")}catch(o){throw p.error({title:"Error",message:"Oops! Something went wrong! Try reloading the page!",position:"topRight"}),o}}function f(r){const{data:s}=r;return s.map(({webformatURL:a,largeImageURL:i,tags:e,likes:t,views:o,comments:g,downloads:y})=>`<div class="photo-card">
          <a class="photo-card__link" href="${i}">
            <img class="photo-card__image" src="${a}" alt="${e}" loading="lazy" />
            <div class="info">
              <p class="info-item"><b>Likes</b> <span class="info-item__wrapper">${t}</span></p>
              <p class="info-item"><b>Views</b> <span class="info-item__wrapper">${o}</span></p>
              <p class="info-item"><b>Comments</b> <span class="info-item__wrapper">${g}</span></p>
              <p class="info-item"><b>Downloads</b> <span class="info-item__wrapper">${y}</span></p>
            </div>
          </a>
        </div>`).join("")}const h=new b(".gallery a");
//# sourceMappingURL=commonHelpers.js.map
