import{i as l,a as b,S as w}from"./assets/vendor-0c7dbcfa.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();let s=1;const p=document.getElementById("search-form"),d=document.querySelector(".gallery"),c=document.querySelector(".js-load");p.addEventListener("submit",E);c.addEventListener("click",L);async function L(){s+=1;try{const r=await m(p.elements.searchQuery.value,s);d.innerHTML+=h(r),s>=r.totalPages&&c.classList.replace("load-more","load-more-hidden"),u.refresh(),g()}catch(r){console.error("error",r),l.error({title:"Error",message:"Oops! Something went wrong! Try reloading the page!",position:"topRight"})}}async function E(r){r.preventDefault(),s=1;const n=r.currentTarget.elements.searchQuery.value;try{const a=await m(n,s);a.data.length===0?(d.innerHTML="",c.classList.replace("load-more","load-more-hidden"),l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight"})):(d.innerHTML=h(a),s<a.totalPages&&c.classList.replace("load-more-hidden","load-more")),u.refresh(),g()}catch(a){console.error("error",a),l.error({title:"Error",message:"Oops! Something went wrong! Try reloading the page!",position:"topRight"})}}function g(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}async function m(r,n){const t=`https://pixabay.com/api/?key=40948305-cf809bb8656872e1f12174930&q=${r}&page=${n}&per_page=${40}&image_type=photo&orientation=horizontal&safesearch=true`;try{const o=await b.get(t);if(o.data&&o.data.hits)return{data:o.data.hits,totalPages:Math.ceil(o.data.totalHits/40)};throw console.error("Invalid response format:",o),new Error("Invalid response format")}catch(o){throw l.error({title:"Error",message:"Oops! Something went wrong! Try reloading the page!",position:"topRight"}),o}}function h(r){const{data:n}=r;return n.map(({webformatURL:a,largeImageURL:i,tags:e,likes:t,views:o,comments:f,downloads:y})=>`<div class="photo-card">
          <a class="photo-card__link" href="${i}">
            <img class="photo-card__image" src="${a}" alt="${e}" loading="lazy" />
            <div class="info">
              <p class="info-item"><b>Likes ${t}</b></p>
              <p class="info-item"><b>Views ${o}</b></p>
              <p class="info-item"><b>Comments ${f}</b></p>
              <p class="info-item"><b>Downloads ${y}</b></p>
            </div>
          </a>
        </div>`).join("")}const u=new w(".gallery a");
//# sourceMappingURL=commonHelpers.js.map
